### ISSUE TITLE
Secret / Whisper rolls should fetch the skill data of the actor in question

### ISSUE THREAD

**Issue by WaakFin** [Wasteland-Ventures-Group/WV-VTT-module#7]
With the current chat macros either correct skill data gets fetched, but the results are (before manually setting them otherwise) public, or with whispers it cannot fetch the data.

In the latter case as the message is not sent as the selected token (Foundry mechanics) and instead as the GM player themselves, macros do not find the data as no character is linked to the GM player.

**Comment by kmoschcau** [comment]
From asking around, it is entirely possible that this is not supported by foundry's chat macros and we would instead need to use script macros. For example you can get the controlled characters with `canvas.tokens.controlled`. You can then pick one out of there and access the actor data with `token.actor.data`. You would then have to create the Roll and ChatMessage just like it is done in the WvActorSheet class.

**Comment by kmoschcau** [comment]
I have determined that this is not in the scope of the system and instead how we add macros to the game. This could only be solved in the system once we ship ready made macros.
